*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZACC_MAPTOP.                      " Global Data
  INCLUDE LZACC_MAPUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZACC_MAPF00                            . " subprograms
  INCLUDE LZACC_MAPI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZACC_MAPF...                      " Subprograms
* INCLUDE LZACC_MAPO...                      " PBO-Modules
* INCLUDE LZACC_MAPI...                      " PAI-Modules
