*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZACC_REGITOP.                     " Global Data
  INCLUDE LZACC_REGIUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZACC_REGIF00                           . " subprograms
  INCLUDE LZACC_REGII00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZACC_REGIF...                     " Subprograms
* INCLUDE LZACC_REGIO...                     " PBO-Modules
* INCLUDE LZACC_REGII...                     " PAI-Modules
